### Numpy(Numerical Python)

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr1.ndim

1

In [4]:
arr1.dtype

dtype('int32')

In [6]:
range(1,10,3)

range(1, 10, 3)

In [9]:
range(1,10,2.3)

TypeError: 'float' object cannot be interpreted as an integer

In [7]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [8]:
np.arange(1,10.3,1.3)

array([ 1. ,  2.3,  3.6,  4.9,  6.2,  7.5,  8.8, 10.1])

In [14]:
a = np.linspace(1,5,10)# start,ending value,number of divisons
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [15]:
a.shape

(10,)

In [16]:
a.size

10

In [17]:
f = np.arange(1,51)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [18]:
f.ndim

1

In [19]:
arr2 = np.array([[1,2,3],[5,6,7]])
arr2

array([[1, 2, 3],
       [5, 6, 7]])

In [20]:
arr2.ndim

2

In [21]:
f.reshape(10,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [26]:
f.reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [23]:
f.reshape(10,3)

ValueError: cannot reshape array of size 50 into shape (10,3)

In [25]:
f.reshape(2,25)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [27]:
f.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [28]:
f.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [29]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [30]:
f.reshape(-1,10)#(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [31]:
f.reshape(10,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [32]:
f.reshape(12,-1)

ValueError: cannot reshape array of size 50 into shape (12,newaxis)

In [33]:
f1 = np.arange(1,26)
f1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [38]:
arr2 = f1.reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
f1.reshape(13,2)

ValueError: cannot reshape array of size 25 into shape (13,2)

In [36]:
f1.reshape(25,-1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [37]:
f1.reshape(-1,25)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [39]:
arr2.ndim

2

In [40]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
arr2.shape

(5, 5)

In [42]:
arr2.size

25

In [45]:
d=np.arange(1,51).reshape(5,1,10)
d

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35, 36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45, 46, 47, 48, 49, 50]]])

In [47]:
d1 =np.arange(1,51).reshape(1,1,50)
d1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
         33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
         49, 50]]])

In [48]:
d1.ndim

3

In [49]:
d1.shape

(1, 1, 50)

In [50]:
d2 =np.arange(1,51).reshape(10,1,5)
d2

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45]],

       [[46, 47, 48, 49, 50]]])

In [51]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
np.ones((10,2),dtype=np.int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [53]:
np.ones((10,2),dtype=np.object)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=object)

In [55]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [56]:
np.zeros((3,4),dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [64]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

- Sorting

In [65]:
a = np.array([2,89,1,23,67,45])
a

array([ 2, 89,  1, 23, 67, 45])

In [66]:
np.sort(a)

array([ 1,  2, 23, 45, 67, 89])

In [72]:
a = np.array([[2,89,1],[23,67,45],[2,3,6]])
a

array([[ 2, 89,  1],
       [23, 67, 45],
       [ 2,  3,  6]])

In [73]:
np.sort(a)

array([[ 1,  2, 89],
       [23, 45, 67],
       [ 2,  3,  6]])

In [74]:
np.sort(a,axis=0)

array([[ 2,  3,  1],
       [ 2, 67,  6],
       [23, 89, 45]])

In [75]:
a.T

array([[ 2, 23,  2],
       [89, 67,  3],
       [ 1, 45,  6]])

In [76]:
a

array([[ 2, 89,  1],
       [23, 67, 45],
       [ 2,  3,  6]])

In [77]:
a = np.array([1,2,3])
b = np.array([7,5,4])
print(a)
print(b)

[1 2 3]
[7 5 4]


In [79]:
np.concatenate((a,b))

array([1, 2, 3, 7, 5, 4])

In [80]:
np.concatenate((b,a),axis=0)

array([7, 5, 4, 1, 2, 3])

- **indexing**

In [99]:
d = np.arange(1,100,2).reshape(2,5,-1)
d

array([[[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19],
        [21, 23, 25, 27, 29],
        [31, 33, 35, 37, 39],
        [41, 43, 45, 47, 49]],

       [[51, 53, 55, 57, 59],
        [61, 63, 65, 67, 69],
        [71, 73, 75, 77, 79],
        [81, 83, 85, 87, 89],
        [91, 93, 95, 97, 99]]])

In [93]:
d[0,0,0] # part,row,column

1

In [94]:
d[1,0,0]

51

In [96]:
d[1,3,2]

85

In [110]:
d[::-1]

array([[[51, 53, 55, 57, 59],
        [61, 63, 65, 67, 69],
        [71, 73, 75, 77, 79],
        [81, 83, 85, 87, 89],
        [91, 93, 95, 97, 99]],

       [[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19],
        [21, 23, 25, 27, 29],
        [31, 33, 35, 37, 39],
        [41, 43, 45, 47, 49]]])

In [111]:
d[-1]

array([[51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [116]:
d[1,2,3]

77

### Mathematical operations

In [124]:
a = [1,2,3]
b = [4,5,6]
#output=[5,7,9]
l=[]
for i in range(len(a)):
    (l.append(a[i]+b[i]))
print(l)

     
    

[5, 7, 9]


In [125]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [126]:
print(a+b)

[5 7 9]


In [127]:
print(a-b)

[-3 -3 -3]


In [128]:
a/b

array([0.25, 0.4 , 0.5 ])

In [131]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [129]:
a%b

array([1, 2, 3], dtype=int32)

In [130]:
a//b

array([0, 0, 0], dtype=int32)

- exponential and log

In [132]:
a

array([1, 2, 3])

In [133]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [134]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125])

In [135]:
np.log2(a)

array([0.       , 1.       , 1.5849625])

In [136]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [142]:
c = np.array([4.6,7.8,3,2.6,9.0,2.01])
c

array([4.6 , 7.8 , 3.  , 2.6 , 9.  , 2.01])

In [143]:
np.floor(c)

array([4., 7., 3., 2., 9., 2.])

In [144]:
np.ceil(c)

array([5., 8., 3., 3., 9., 3.])

In [141]:
np.round_(c)

array([5., 8., 3., 3., 9.])

### Random

In [145]:
from numpy import random

In [152]:
random.randint(100)

46

In [153]:
random.randint(100,size=(5))

array([82, 99, 57, 41, 33])

In [155]:
random.randint(100,size=(5,4))

array([[29, 63, 52, 32],
       [ 9, 63, 48, 10],
       [34, 93, 43, 18],
       [76,  7, 19,  8],
       [96,  5,  6, 35]])

In [156]:
random.rand(5) # 0 to 1

array([0.09931408, 0.90117439, 0.5467599 , 0.05835432, 0.58972914])

In [157]:
random.rand(5,5)

array([[0.09465293, 0.18229191, 0.71408191, 0.8596162 , 0.51346999],
       [0.48832068, 0.24971726, 0.44316561, 0.74587973, 0.05064095],
       [0.18862621, 0.47918205, 0.94553648, 0.87553228, 0.57497115],
       [0.57743849, 0.98677495, 0.42273585, 0.4924201 , 0.77801373],
       [0.42928699, 0.70608592, 0.30271129, 0.72509327, 0.53776496]])

In [158]:
random.choice([3,2,4],size=(3,5))

array([[4, 3, 2, 4, 4],
       [2, 3, 3, 2, 3],
       [4, 3, 4, 2, 3]])

In [162]:
random.choice([3,2,4],p=[0.7,0.1,0.2],size=(100))

array([3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 3, 3, 4,
       3, 3, 3, 3, 3, 2, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 4, 4, 4, 3, 3, 4, 4,
       4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 4, 3, 3, 4, 3, 4, 3, 3, 4, 4])

## Pandas
 
 - pandas is also one of the library in python which is used to perform data analysis and data manipulation
 - data analysis---->Cleaning,processing,modeling and inspecting data
 - data manipulation---->adding,deleting and modification
 

- creating data in 2 types
    - series
    - Data Frame

In [163]:
import pandas as pd

In [164]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [165]:
pd.Series(np.array([1,2,3,4]))

0    1
1    2
2    3
3    4
dtype: int32

In [166]:
pd.Series({"a":2,"b":3})

a    2
b    3
dtype: int64

In [169]:
pd.Series(np.array([1,2,3,4]),index=["a","b","c","d"])

a    1
b    2
c    3
d    4
dtype: int32